/*
 * Veritone Build and Release API
 *
 * Build and release API for Veritone
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package handlers

import (
	"encoding/json"
	"net/http"

	log "github.com/sirupsen/logrus"

	"github.com/aeekayy/go-api-base/pkg/models"
)

const (
	postUserQueryCols = "username"
	//postUserQueryDistinctCols = "service_id,environment_id"
	postUserQueryTableName = "users"
)

// PostUser POST user handler for creating a user
type PostUser struct {
	BaseHandler
}

// PostUserRequest request for user
type PostUserRequest struct {
	Username string `json:"username" yaml:"username"`
}

// PostUserResponse handles the response for POST user with status and data
type PostUserResponse struct {
	Status int           `json:"status" yaml:"status"`
	Data   []models.User `json:"data" yaml:"data"`
}

// ServeHTTP main function for handler
func (h PostUser) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.Name = "PostUserRoute"
	h.Category = CategoryUser

	var req PostUserRequest
	var users []models.User

	err := json.NewDecoder(r.Body).Decode(&req)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// retrieve the result
	user := models.User{
		Username: req.Username,
	}

	// retrieve the result
	/*h.DB.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "username"}},
		DoUpdates: clause.AssignmentColumns([]string{"updated_date_time"}),
	}).Select("Username", "Kvp").Create(&user)*/
	h.DB.Select("Username", "Password", "Kvp").Create(&user)

	// append the pipeline
	users = append(users, user)

	// wrap the result in a response
	resp := PostUserResponse{
		Status: http.StatusOK,
		Data:   users,
	}

	respJSON, err := json.Marshal(resp)
	if err != nil {
		log.Error("Could not retrieve event errors")
		http.Error(w, "Could not retrieve data", http.StatusUnprocessableEntity)
		return
	}

	h.WriteJSON(w, http.StatusOK, respJSON)
}
