/*
 * Veritone Build and Release API
 *
 * Build and release API for Veritone
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gorilla/mux"
	"github.com/jinzhu/gorm"

	handlers "github.com/aeekayy/go-api-base/pkg/api/handlers"
)

const (
	allowedOriginHosts = "api.aeekay.co,app.aeekay.co"
)

var noCacheHeaders = map[string]string{
	"Expires":         time.Unix(0, 0).Format(time.RFC1123),
	"Cache-Control":   "no-cache, private, max-age=0",
	"Pragma":          "no-cache",
	"X-Accel-Expires": "0",
}


type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter(db *gorm.DB) *mux.Router {
	routes := getRoutes(db)

	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

func getRoutes(db *gorm.DB) Routes {
	return Routes{
		Route{
			"Index",
			"GET",
			"/v2/",
			handlers.Index,
		},

		Route{
			"Ping",
			http.MethodGet, 
			"v2/ping", 
			pingHandler,
		},

		Route{
			"GetEvents",
			http.MethodGet,
			"/v2/events",
			handlers.GetEvents{DB: db, CORS: allowedOriginHosts}.ServeHTTP,
		}, 
	}
}
