/*
 * Veritone Build and Release API
 *
 * Build and release API for Veritone
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

import ()

// Credentials represents service credentials
type Credentials struct {
	Username string `json:"username,omitempty" gorm:"type:varchar(256);"`
	Password string `json:"password,omitempty" gorm:"type:varchar(512);"`
}
