/*
 * Veritone Build and Release API
 *
 * Build and release API for Veritone
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
)

type Event struct {
	EventID         uuid.UUID      `json:"event_id,omitempty" gorm:"primary_key;default:uuid_generate_v4();not null;"`
	Name            string         `json:"name,omitempty" gorm:"type:varchar(1024);"`
	Kvp             datatypes.JSON `json:"kvp" gorm:"default:'{}'"`
	CreatedDateTime time.Time      `json:"created_date_time,omitempty" gorm:"default:timezone('utc'::text, now())"`
	UpdatedDateTime time.Time      `json:"updated_date_time,omitempty" gorm:"default:timezone('utc'::text, now())"`
}
